# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('0', 'Office'), ('1', 'Academic')], default='office', max_length=8),
        ),
    ]
