# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='static/myApp/Images'),
        ),
    ]
