# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
