# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_offer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='title',
            new_name='hey',
        ),
    ]
