# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0027_auto_20170815_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Post'),
        ),
        migrations.AddField(
            model_name='offer',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
