# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_auto_20170815_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='offer',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reason',
            field=models.TextField(max_length=128),
        ),
    ]
