# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_auto_20170815_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='username',
            new_name='userOffer',
        ),
    ]
