# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_auto_20170815_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='reason',
            field=models.TextField(default='N/A', max_length=128),
        ),
    ]
