# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_auto_20170815_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemOffer', to='myApp.Post'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemBuy', to='myApp.Post'),
        ),
    ]
