# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('0', 'Office'), ('1', 'Academic')], max_length=8),
        ),
    ]
