# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20170726_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('0', 'Office'), ('1', 'Academic')], default='office', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
