# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_auto_20170726_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='degree_program',
            new_name='degreeprogram_or_office',
        ),
    ]
