# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_auto_20170726_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='degreeprogram_or_office',
            new_name='Degree_Program_or_Office',
        ),
    ]
