# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_auto_20170727_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_username',
            new_name='username',
        ),
    ]
