# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_post_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course_name',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
